# Linear Algebra with NumPy and SciPy

## Numpy

NumPy offers efficient dense-array operations that underpin many
quantum-simulation tasks.

### Matrix–Matrix and Matrix–Vector Multiplication

Understanding an operator’s action on itself and on quantum states is
key: matrix–matrix products show operator composition, while
matrix–vector products illustrate state evolution.

In [1]:
import numpy as np

# Define a 2×2 matrix and a 2-vector
A = np.array([[1, 2], [3, 4]])
v = np.array([5, 6])

# Matrix–matrix product
c = A @ A  # same as A.dot(A)
display("A @ A =", c)

# Matrix–vector product
w = A @ v  # same as A.dot(v)
display("A @ v =", w)

'A @ A ='

array([[ 7, 10],
       [15, 22]])

'A @ v ='

array([17, 39])

### Eigenvalues and Eigenvectors of a dense matrix

Eigen-decomposition reveals the energy spectrum and stationary states of
a quantum system, making it fundamental for analysis.

In [2]:
w, v = np.linalg.eig(A)
display("Eigenvalues:", w)
display("Eigenvectors (as columns):\n", v)

'Eigenvalues:'

array([-0.37228132,  5.37228132])

'Eigenvectors (as columns):\n'

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

### Kronecker Product

The Kronecker product builds operators on composite systems by combining
subsystem operators into a larger Hilbert space.

In [3]:
B = np.array([[0, 1], [1, 0]])  # Pauli-X matrix
kron = np.kron(A, B)
display("A ⊗ B =", kron)

'A ⊗ B ='

array([[0, 1, 0, 2],
       [1, 0, 2, 0],
       [0, 3, 0, 4],
       [3, 0, 4, 0]])

## SciPy

SciPy extends NumPy with advanced routines and sparse data structures,
enabling efficient handling of larger, structured problems.

### Some Useful Functions

Determinant, inverse, and norm computations provide quick diagnostics on
operator properties.

In [4]:
import scipy.linalg as la

det = la.det(A)
inv = la.inv(A)
norm_f = la.norm(A)
display(det, inv, norm_f)

np.float64(-2.0)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

np.float64(5.477225575051661)

### Solving Linear Systems

Solving linear systems (Ax = b) appears in contexts from steady states
to implicit integration schemes.

In [5]:
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 11])
x = np.linalg.solve(A, b)
display("Solution x=", x)

'Solution x='

array([1., 2.])

### Sparse Matrices

Sparse formats store only nonzeros, saving memory and accelerating
matrix–vector operations for large systems. Here we use the **COO**
(coordinate) format, which is simple and efficient for constructing
sparse matrices.

In [6]:
from scipy import sparse

# Create a sparse COO matrix
i = [0, 0, 1, 2, 4] # row indices
j = [0, 4, 2, 1, 0] # column indices
data = [7, 1, 2, 3, 4] # nonzero values
coo = sparse.coo_matrix((data, (i, j)), shape=(5, 5))
coo

<COOrdinate sparse matrix of dtype 'int64'
    with 5 stored elements and shape (5, 5)>

We can convert the COO matrix to other formats, such as **CSR**
(Compressed Sparse Row), which is more efficient for matrix–vector
products.

In [7]:
# Convert COO to CSR format
csr = coo.tocsr()
csr

<Compressed Sparse Row sparse matrix of dtype 'int64'
    with 5 stored elements and shape (5, 5)>

Matrix–vector products are efficient with sparse matrices, as they only
compute the nonzero contributions.

In [8]:
# Matrix–vector product
v = np.array([1, 2, 3, 4, 5])
w = coo @ v  # same as coo.dot(v)
w

array([12,  6,  6,  0,  4])

### Eigenvalues of Sparse Matrices

Krylov-subspace methods extract a few extremal eigenvalues from large
sparse operators, essential when full diagonalization is infeasible.

In [9]:
from scipy.sparse.linalg import eigs

# Compute the 2 largest-magnitude eigenvalues of coo
vals, vecs = eigs(coo, k=2)
display("Sparse eigenvalues:", vals)

'Sparse eigenvalues:'

array([7.53112887+0.j, 2.44948974+0.j])